// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(BddContext))]
    [Migration("20250202133243_FixFilmPlotSeed")]
    partial class FixFilmPlotSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("WebApi.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            Rating = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 2,
                            Rating = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 3,
                            Rating = 8,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebApi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imdb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Imdb")
                        .IsUnique();

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            Imdb = "tt0111161",
                            ImdbRating = "9.3",
                            Name = "The Shawshank Redemption",
                            Plot = "Two imprisoned men bond over a number of years.",
                            Poster = "",
                            Year = ""
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            Imdb = "tt0068646",
                            ImdbRating = "9.2",
                            Name = "The Godfather",
                            Plot = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Poster = "",
                            Year = ""
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            Imdb = "tt0468569",
                            ImdbRating = "9.0",
                            Name = "The Dark Knight",
                            Plot = "When the menace known as the Joker emerges, he plunges Gotham into chaos.",
                            Poster = "",
                            Year = ""
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Drama",
                            Imdb = "tt0109830",
                            ImdbRating = "8.8",
                            Name = "Forrest Gump",
                            Plot = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man.",
                            Poster = "",
                            Year = ""
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "defaultPassword",
                            Pseudo = "Alice",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Password = "defaultPassword",
                            Pseudo = "Bob",
                            Role = 0
                        });
                });

            modelBuilder.Entity("WebApi.Models.Favourite", b =>
                {
                    b.HasOne("WebApi.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
